- name: Add all mysql hosts to /etc/hosts
  ansible.builtin.lineinfile: 
    path: /etc/hosts
    line: "{{ item }} {{ hostvars[item].ansible_hostname }}"
    state: present
  loop: "{{ ansible_play_hosts }}"
  become: true