- name: Download GPG keys ({{ ansible_os_family }} family)
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "/tmp/{{ item.filename }}"
    mode: '0644'
  loop: "{{ gpg_keys }}"
  when: ansible_os_family == "RedHat"

- name: Import GPG keys ({{ ansible_os_family }} family)
  ansible.builtin.rpm_key:
    state: present
    key: "/tmp/{{ item.filename }}"
  loop: "{{ gpg_keys }}"
  when: ansible_os_family == "RedHat"